/**
 * uuid farm
 * A farm for abandoned UUIDs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UuidFarm);
  }
}(this, function(expect, UuidFarm) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UuidFarm.Farm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Farm', function() {
    it('should create an instance of Farm', function() {
      // uncomment below and update the code to test Farm
      //var instane = new UuidFarm.Farm();
      //expect(instance).to.be.a(UuidFarm.Farm);
    });

    it('should have the property uuids (base name: "uuids")', function() {
      // uncomment below and update the code to test the property uuids
      //var instane = new UuidFarm.Farm();
      //expect(instance).to.be();
    });

    it('should have the property adopted (base name: "adopted")', function() {
      // uncomment below and update the code to test the property adopted
      //var instane = new UuidFarm.Farm();
      //expect(instance).to.be();
    });

    it('should have the property surrendered (base name: "surrendered")', function() {
      // uncomment below and update the code to test the property surrendered
      //var instane = new UuidFarm.Farm();
      //expect(instance).to.be();
    });

  });

}));
