/**
 * uuid farm
 * A farm for abandoned UUIDs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UuidFarm);
  }
}(this, function(expect, UuidFarm) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UuidFarm.Uuid();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Uuid', function() {
    it('should create an instance of Uuid', function() {
      // uncomment below and update the code to test Uuid
      //var instane = new UuidFarm.Uuid();
      //expect(instance).to.be.a(UuidFarm.Uuid);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new UuidFarm.Uuid();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new UuidFarm.Uuid();
      //expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      //var instane = new UuidFarm.Uuid();
      //expect(instance).to.be();
    });

    it('should have the property surrenderDate (base name: "surrenderDate")', function() {
      // uncomment below and update the code to test the property surrenderDate
      //var instane = new UuidFarm.Uuid();
      //expect(instance).to.be();
    });

    it('should have the property adoptionDate (base name: "adoptionDate")', function() {
      // uncomment below and update the code to test the property adoptionDate
      //var instane = new UuidFarm.Uuid();
      //expect(instance).to.be();
    });

  });

}));
