/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"log"
	"net/http"

	firebase "firebase.google.com/go"
	"github.com/jesse0michael/uuid-farm/pkg/uuids"
)

func main() {
	log.Printf("Server started")

	ctx := context.Background()
	conf := &firebase.Config{ProjectID: "uuid-farm"}
	app, err := firebase.NewApp(ctx, conf)
	if err != nil {
		log.Fatalln(err)
	}

	client, err := app.Firestore(ctx)
	if err != nil {
		log.Fatalln(err)
	}
	defer client.Close()

	DefaultAPIService := uuids.NewDefaultApiService(client)
	DefaultAPIController := uuids.NewDefaultApiController(DefaultAPIService)

	router := uuids.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
