/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Uuid struct {

	Name string `json:"name"`

	Tag string `json:"tag,omitempty"`

	SurrenderDate string `json:"surrenderDate,omitempty"`

	AdoptionDate string `json:"adoptionDate,omitempty"`
}
