/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	{
		"AdoptUUID",
		strings.ToUpper("Post"),
		"/v1/uuids",
		AdoptUUID,
	},

	{
		"GetUUID",
		strings.ToUpper("Get"),
		"/v1/uuids/{id}",
		GetUUID,
	},

	{
		"GetUUIDs",
		strings.ToUpper("Get"),
		"/v1/uuids",
		GetUUIDs,
	},

	{
		"RootGet",
		strings.ToUpper("Get"),
		"/v1/",
		RootGet,
	},

	{
		"SurrenderUUID",
		strings.ToUpper("Post"),
		"/v1/uuids/{id}",
		SurrenderUUID,
	},

	{
		"UpdateUUID",
		strings.ToUpper("Put"),
		"/v1/uuids/{id}",
		UpdateUUID,
	},
}
