/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/uuids"
	//
	sw "./uuids"
)

func main() {
	log.Printf("Server started")

    service := sw.NewAPIService()
    controller := sw.NewController(service)
	router := sw.NewRouter(controller)

	log.Fatal(http.ListenAndServe(":8080", router))
}
