/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/jesse0michael/uuid-farm/server/uuids"
)

func main() {
	log.Printf("Server started")

	router := uuids.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
