/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uuids

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// AdoptUUID - Adopt uuid
func (s *DefaultApiService) AdoptUUID(id string) (interface{}, error) {
	// TODO - update AdoptUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'AdoptUUID' not implemented")
}

// GetFarm - Farm stats
func (s *DefaultApiService) GetFarm() (interface{}, error) {
	// TODO - update GetFarm with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetFarm' not implemented")
}

// GetUUID - Get uuid that&#39;s on the farm
func (s *DefaultApiService) GetUUID(id string) (interface{}, error) {
	// TODO - update GetUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetUUID' not implemented")
}

// GetUUIDs - Get uuids
func (s *DefaultApiService) GetUUIDs() (interface{}, error) {
	// TODO - update GetUUIDs with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetUUIDs' not implemented")
}

// SurrenderUUID - Surrender uuid
func (s *DefaultApiService) SurrenderUUID(id string) (interface{}, error) {
	// TODO - update SurrenderUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SurrenderUUID' not implemented")
}

// UpdateUUID - Update uuid
func (s *DefaultApiService) UpdateUUID(id string, uuid Uuid) (interface{}, error) {
	// TODO - update UpdateUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateUUID' not implemented")
}
