/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uuids

import (
	"encoding/json"
	"net/http"

	"github.com/gorilla/mux"
)

type Controller struct {
	service Servicer
}

func NewController(s *Servicer) RouteBinder {
	return &Controller{}
}

type Servicer interface {
	AdoptUUID(string) (interface{}, error)
	GetFarm() (interface{}, error)
	GetUUID(string) (interface{}, error)
	GetUUIDs() (interface{}, error)
	SurrenderUUID(string) (interface{}, error)
	UpdateUUID(string, Uuid) (interface{}, error)
}

// move to separate file
type APIService struct {
}

func NewAPIService() Servicer {
	return &APIService{}
}

// AdoptUUID - Adopt uuid
func (s *APIService) AdoptUUID(id string) (interface{}, error) {
	return nil, nil
}

// GetFarm - Farm stats
func (s *APIService) GetFarm() (interface{}, error) {
	return nil, nil
}

// GetUUID - Get uuid that's on the farm
func (s *APIService) GetUUID(id string) (interface{}, error) {
	return nil, nil
}

// GetUUIDs - Get uuids
func (s *APIService) GetUUIDs() (interface{}, error) {
	return nil, nil
}

// SurrenderUUID - Surrender uuid
func (s *APIService) SurrenderUUID(id string) (interface{}, error) {
	return nil, nil
}

// UpdateUUID - Update uuid
func (s *APIService) UpdateUUID(id string, uuid Uuid) (interface{}, error) {
	return nil, nil
}

// -------

// AdoptUUID - Adopt uuid
func (c *Controller) AdoptUUID(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id := params["id"]

	result, err := c.service.AdoptUUID(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetFarm - Farm stats
func (c *Controller) GetFarm(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetFarm()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetUUID - Get uuid that's on the farm
func (c *Controller) GetUUID(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id := params["id"]

	result, err := c.service.GetUUID(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetUUIDs - Get uuids
func (c *Controller) GetUUIDs(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetUUIDs()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// SurrenderUUID - Surrender uuid
func (c *Controller) SurrenderUUID(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id := params["id"]

	result, err := c.service.SurrenderUUID(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// UpdateUUID - Update uuid
func (c *Controller) UpdateUUID(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id := params["id"]

	uuid := &Uuid{}
	if err := json.NewDecoder(r.Body).Decode(&uuid); err != nil {
		w.WriteHeader(500)
		return
	}
	result, err := c.service.UpdateUUID(id, uuid)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
