/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uuids

type ModelError struct {

	Code int32 `json:"code"`

	Message string `json:"message"`
}
