/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uuids

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

type RouteBinder interface {
	AdoptUUID(http.ResponseWriter, *http.Request)
	GetFarm(http.ResponseWriter, *http.Request)
	GetUUID(http.ResponseWriter, *http.Request)
	GetUUIDs(http.ResponseWriter, *http.Request)
	SurrenderUUID(http.ResponseWriter, *http.Request)
	UpdateUUID(http.ResponseWriter, *http.Request)
}

func NewRouter(binder RouteBinder) *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes(binder) {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func routes(binder RouteBinder) Routes {
	return Routes{
		{
			"AdoptUUID",
			strings.ToUpper("Post"),
			"/v1/uuids",
			binder.AdoptUUID,
		},
		{
			"GetFarm",
			strings.ToUpper("Get"),
			"/v1/",
			binder.GetFarm,
		},
		{
			"GetUUID",
			strings.ToUpper("Get"),
			"/v1/uuids/{id}",
			binder.GetUUID,
		},
		{
			"GetUUIDs",
			strings.ToUpper("Get"),
			"/v1/uuids",
			binder.GetUUIDs,
		},
		{
			"SurrenderUUID",
			strings.ToUpper("Post"),
			"/v1/uuids/{id}",
			binder.SurrenderUUID,
		},
		{
			"UpdateUUID",
			strings.ToUpper("Put"),
			"/v1/uuids/{id}",
			binder.UpdateUUID,
		},
	}
}

func EncodeJSONResponse(i interface{}, status *int, w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if status != nil {
		w.WriteHeader(*status)
	} else {
		w.WriteHeader(http.StatusOK)
	}

	return json.NewEncoder(w).Encode(i)
}
