/**
 * uuid farm
 * A farm for abandoned UUIDs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Farm {
    'uuids': number;
    'adopted': number;
    'surrendered': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuids",
            "baseName": "uuids",
            "type": "number"
        },
        {
            "name": "adopted",
            "baseName": "adopted",
            "type": "number"
        },
        {
            "name": "surrendered",
            "baseName": "surrendered",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Farm.attributeTypeMap;
    }
}

