/**
 * uuid farm
 * A farm for abandoned UUIDs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Uuid {
    'id': string;
    'name'?: string;
    'tag'?: string;
    'surrenderDate'?: string;
    'adoptionDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        },
        {
            "name": "surrenderDate",
            "baseName": "surrenderDate",
            "type": "string"
        },
        {
            "name": "adoptionDate",
            "baseName": "adoptionDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Uuid.attributeTypeMap;
    }
}

