/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uuids

import (
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	Routes() Routes
	AdoptUUID(http.ResponseWriter, *http.Request)
	GetFarm(http.ResponseWriter, *http.Request)
	GetUUID(http.ResponseWriter, *http.Request)
	GetUUIDs(http.ResponseWriter, *http.Request)
	SurrenderUUID(http.ResponseWriter, *http.Request)
	UpdateUUID(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	AdoptUUID(string) (interface{}, error)
	GetFarm() (interface{}, error)
	GetUUID(string) (interface{}, error)
	GetUUIDs() (interface{}, error)
	SurrenderUUID(string) (interface{}, error)
	UpdateUUID(string, Uuid) (interface{}, error)
}
