/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uuids

type Farm struct {

	Uuids int32 `json:"uuids"`

	Adopted int32 `json:"adopted"`

	Surrendered int32 `json:"surrendered"`
}
