/*
 * uuid farm
 *
 * A farm for abandoned UUIDs
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uuids

type Uuid struct {

	Id string `json:"id"`

	Name string `json:"name,omitempty"`

	Tag string `json:"tag,omitempty"`

	SurrenderDate string `json:"surrenderDate,omitempty"`

	AdoptionDate string `json:"adoptionDate,omitempty"`
}
