/**
 * uuid farm
 * A farm for abandoned UUIDs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Uuid model module.
 * @module model/Uuid
 * @version v1
 */
class Uuid {
    /**
     * Constructs a new <code>Uuid</code>.
     * @alias module:model/Uuid
     * @param id {String} 
     */
    constructor(id) { 
        
        Uuid.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Uuid</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Uuid} obj Optional instance to populate.
     * @return {module:model/Uuid} The populated <code>Uuid</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Uuid();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('surrenderDate')) {
                obj['surrenderDate'] = ApiClient.convertToType(data['surrenderDate'], 'Date');
            }
            if (data.hasOwnProperty('adoptionDate')) {
                obj['adoptionDate'] = ApiClient.convertToType(data['adoptionDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Uuid.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Uuid.prototype['name'] = undefined;

/**
 * @member {String} tag
 */
Uuid.prototype['tag'] = undefined;

/**
 * @member {Date} surrenderDate
 */
Uuid.prototype['surrenderDate'] = undefined;

/**
 * @member {Date} adoptionDate
 */
Uuid.prototype['adoptionDate'] = undefined;






export default Uuid;

