openapi: 3.0.2
info:
  description: A farm for abandoned UUIDs
  title: uuid farm
  version: v1
servers:
- description: uuid farm
  url: http://localhost:8080/v1
paths:
  /:
    get:
      description: Returns farm statistics.
      operationId: getFarm
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/farm'
          description: Success response
      summary: Get Farm Stats
  /uuids:
    get:
      description: Returns all uuids.
      operationId: getUUIDs
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/uuid'
                type: array
          description: uuid array response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
          description: unexpected error
      summary: Get UUIDs
    post:
      description: Adopt a previously surrendered, not yet adopted, uuid at random.
      operationId: adoptUUID
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uuid'
          description: uuid response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
          description: unexpected error
      summary: Adopt UUID
  /uuids/{id}:
    get:
      description: Returns information on a uuid by its id. Rejects invalid and not
        found uuids.
      operationId: getUUID
      parameters:
      - description: uuid
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uuid'
          description: uuid response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
          description: unexpected error
      summary: Get UUID
    post:
      description: Adds a new uuid to the farm to become available for adoption. Rejects
        invalid or duplicate uuids.
      operationId: surrenderUUID
      parameters:
      - description: uuid
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uuid'
          description: uuid response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
          description: unexpected error
      summary: Surrender UUID
    put:
      description: Update uuid metadata. Rejects invalid or not found uuids.
      operationId: updateUUID
      parameters:
      - description: uuid
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/uuid'
        description: uuid
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uuid'
          description: uuid response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
          description: unexpected error
      summary: Update UUID
components:
  schemas:
    uuid:
      example:
        name: name
        tag: tag
        adoptionDate: 2000-01-23
        surrenderDate: 2000-01-23
      properties:
        id:
          type: string
        name:
          type: string
        tag:
          type: string
        surrenderDate:
          format: date
          type: string
        adoptionDate:
          format: date
          type: string
      required:
      - id
      type: object
    apiError:
      properties:
        code:
          example: 400
          format: int32
          type: integer
        message:
          example: Bad request.
          type: string
      required:
      - code
      - message
      type: object
    farm:
      example:
        uuids: 10
      properties:
        uuids:
          example: 10
          type: integer
        adopted:
          example: 2
          type: integer
        surrendered:
          example: 8
          type: integer
      required:
      - adopted
      - surrendered
      - uuids
