name: Release Workflow
on:  
  push:
    tags:
    - '*'
jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release UUID Farm
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        mkdir secrets
        echo "${{ secrets.FIRESTORE_CREDENTIALS }}" > secrets/firebase_credentials.json
        docker build -t docker.pkg.github.com/jesse0michael/uuid-farm/uuid-farm:${REF##*/} .
      
    - name: Publish
      run: |
        docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.GITHUB_SECRET }}
        docker push docker.pkg.github.com/jesse0michael/uuid-farm/uuid-farm:${REF##*/}
