name: Release Workflow
on:  
  push:
    tags:
    - '*'

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release UUID Farm
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        docker build \
          -t docker.pkg.github.com/jesse0michael/uuid-farm/uuid-farm:${REF##*/} \
          -t registry.heroku.com/uuid-farm/web .
      
    - name: Publish
      run: |
        docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.GITHUB_SECRET }}
        docker push docker.pkg.github.com/jesse0michael/uuid-farm/uuid-farm:${REF##*/}
        docker login registry.heroku.com -u Jesse0Michael -p ${{ secrets.HEROKU_API_KEY }}
        docker push registry.heroku.com/uuid-farm/web
        
    - name: Deploy
      uses: "actions/heroku@master"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release web -a uuid-farm    
