name: Release Workflow
on:  
  push:
    tags:
    - '*'

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release UUID Farm
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com
        scope: '@jesse0michael'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_SECRET }}

    - name: Build
      run: |
        docker build \
          -t docker.pkg.github.com/jesse0michael/uuid-farm/uuid-farm:${REF##*/} \
          -t registry.heroku.com/uuid-farm/web .
      
    - name: Publish Server
      run: |
        docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.GITHUB_SECRET }}
        docker push docker.pkg.github.com/jesse0michael/uuid-farm/uuid-farm:${REF##*/}
        docker login registry.heroku.com -u Jesse0Michael -p ${{ secrets.HEROKU_API_KEY }}
        docker push registry.heroku.com/uuid-farm/web
      
    - name: Publish Client
      run: |
        cd client/js
        npm install
        npm run build
        npm publish 
      
    - name: Deploy
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release web -a uuid-farm    
