/**
 * uuid farm
 * A farm for abandoned UUIDs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UuidFarm);
  }
}(this, function(expect, UuidFarm) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UuidFarm.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('adoptUUID', function() {
      it('should call adoptUUID successfully', function(done) {
        //uncomment below and update the code to test adoptUUID
        //instance.adoptUUID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFarm', function() {
      it('should call getFarm successfully', function(done) {
        //uncomment below and update the code to test getFarm
        //instance.getFarm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUUID', function() {
      it('should call getUUID successfully', function(done) {
        //uncomment below and update the code to test getUUID
        //instance.getUUID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUUIDs', function() {
      it('should call getUUIDs successfully', function(done) {
        //uncomment below and update the code to test getUUIDs
        //instance.getUUIDs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('surrenderUUID', function() {
      it('should call surrenderUUID successfully', function(done) {
        //uncomment below and update the code to test surrenderUUID
        //instance.surrenderUUID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUUID', function() {
      it('should call updateUUID successfully', function(done) {
        //uncomment below and update the code to test updateUUID
        //instance.updateUUID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
